### ISSUE TITLE
Threads slowly eating memory ?

### ISSUE THREAD

**Issue by metalwolf** [krakjoe/pthreads#531] opened 2015-12-12 16:43 UTC
Hi @krakjoe 

I got the threaded server running for approx 48 hours, serving approx 1 million requests, and with constant 150-250 threads at the same time. 

After those 48 hours I noticed a strange behaviour, it is very slowly eating memory:

![memory](https://cloud.githubusercontent.com/assets/1404459/11762867/8175ba0c-a0ba-11e5-96fc-dbaabf053da7.png)
![threads](https://cloud.githubusercontent.com/assets/1404459/11762868/817c8c10-a0ba-11e5-84d9-2bd7601b44a7.png)

Making a fast calculation that would give approx 5Gb / 1M = 5K / thread 
Something which is totally unseen on few threads / fast programs but on a long way run become visible.

On the manuals it just says that when the thread "run" ends, the thread is destroyed. Did I miss something ? Some garbage collector missing like in pools ( I dont use pools/workers) ? The main server only keeps the array of threaded clients and unset the clients when they are terminated "normally" or "killed for any reason"

mainly:

mainloop
{
  if (have to create client)
  {
     create client
     $clients[] = the new client
  }

  foreach(clients as client)
    if (client->isTerminated())
       unset(clients[this client])   
}

The quantity of clients effectively stays near 100-200 as reported on screen.
So the server should "not" eat the memory by itself ?
I first thought of a local PHP error I left , but it seems not.

The interesting thing is that I destroy the threads but the CPU still is high. I mean, when I start the server it jump to 150 threads immediatly for the load but uses 5-10% CPU, and the CPU time is quite proportional to the quantity of memory.
Threads are not fully destroyed and uses CPU and memory?

Any ideas ? what could I do to help to find the error if it's thread related ?

**Comment by metalwolf** [comment] 2015-12-14 03:37
Trying to isolate the problem on a simple test program, will tell you when I can validate something :)

**Comment by krakjoe** [comment] 2015-12-14 07:12
pthreads v3 uses the same API to destroy threads that ISAPI does, or mod_php in a worker mpm Apache: It should clean up completely.

I say should because you can see that some libraries do rely on process shutdown to destroy global string tables, so valgrind will report that there are leaks from places like libxml or curl, these can be ignored.

Regardless of whether it should  work, this isn't a great architecture ... creating and destroying so many threads is not a good idea. It is expensive to create a thread, it requires duplicating the environment of the interpreter and all user code, if you're going to start a thread, then keep it around as long as possible.

Happy to investigate if you can come up with a test case ...

**Comment by metalwolf** [comment] 2015-12-26 23:34
Hi @krakjoe, i tried this simple test and it eats extremely fast the memory too.
The interesting part is that PHP does not report the memory, so it's not something that happens into the main variables area.

some 12Gb virtual and 2GB resident after approx a min to work.
I thought it was something related to the structures , sockets etc but it seems it's the very same pthreads kernel that does not release something.

The example does nothings by itself, just to focus on the fast memory loss..
Maybe I am wrong, but I understood the threaded objects are removed from memory when they are no more linked what should do the unset $this->client[$num];

Could it be some garbage collecter that does not happen ? 

```
<?php

class Client extends Thread
{
  private $num;
  private $hasrunned = false;

  public function __construct($num)
  {
    $this->num = $num;
  }
    
  public function hasRunned()
  {
    return $this->hasrunned;
  }
  
  public function run()
  {
    // wait for 1 second (suppose we are processing something heavy)
    $this->synchronized(function($thread) { $thread->wait(1000000); }, $this);
    $this->hasrunned = true;
    return;
  }
  
}

class Server
{
  private $clients = array();
  
  public function __construct() {}

  public function addClient($num)
  {
    $client = new Client($num);
    $client->start();
    $this->clients[$num] = $client;
  }

  public function run()
  {
    $maincounter = 0;
    $mainloop = true;
    while ($mainloop)
    {
      $this->addClient($maincounter);

      foreach($this->clients as $k => $client)
      {
        if ($client->isTerminated())
        {
          // notificar crashed thread id
          $id = $client->getThreadId();
          
          print "Client crashed: " . $k . ' - ' . $id . "\n";
          unset($this->clients[$k]);
        }
        else if ($client->hasRunned())
        {
          unset($this->clients[$k]);
        }
      }
      
      $maincounter++;

      if ($maincounter % 500 == 0)
        print "Clients #: ".sizeof($this->clients) . " - " . (memory_get_usage()/1000000) . "MB\n";
    } 
  }
}

$server = new Server();
$server->run();

?>
```

**Comment by 2072** [comment] 2015-12-27 12:38
Note that `unset()` does not immediately release memory, If you want the memory to be released assign something else such as `null` before calling `unset()`.

This might not change anything if there is an actual memory leak but this way you make sure that Threads internal Destructors are called when you think they should be.

**Comment by metalwolf** [comment] 2015-12-27 23:00
Hi John, thanks. Yes indeed I tried that and also the 

```
        gc_mem_caches();
        gc_collect_cycles();
```

The memory is still growing. 
:D

**Comment by krakjoe** [comment] 2015-12-28 08:25
```unset``` should immediately release memory, the only difference between $this->thing = null and unset($this->thing) is that the former will retain the entry in the properties store and so use *more* memory.

Running the code above, I cannot see any leak, memory usage goes up and down both reported by Zend and ps, so, what am I looking at ?

**Comment by metalwolf** [comment] 2015-12-28 19:00
Hi @krakjoe 

I stat the following graphics:
In blue, this is the reported memory in Mb by PHP (approx .6 Mb constantly)
In orange, it's the real resident memory ovr time (approx 3 hours in this graphic)
1 million threads executed during those 3 hours.

The orange line tends to be a 4K memory / threads eaten.
The grey dots are the quantity of threads / second procesed.

My conclusion of this graphic is:
- There are approx 4K of memory eaten and not released for each thread
(some missing free() on some structure somewhere)
- The quantity of used memory is inversed proportional to the CPU time to process the threads,
so the used memory have a direct impact on CPU use, so the structure not released has to be processed by the CPU

Since you use the TRSM engine of PHP I don't think it's the threads themselves that are eating the memory, but something into the main thread to control the threads. The monitor ?
At a glance I imagine something between switch contexts, search into a hash table, into the monitor maybe ? Some hast table that is only growing and not free'd ? some missing realloc for change of size of structures ?

Hope this will help you seeing where to search the problem ? 

Thanks a lot anyway for this wonderfull library!

- Phil

**Comment by cpugourou** [comment] 2016-01-19 01:07
I am having the exact same problem but with lesser threads. Memory grows by 1Meg for me until reaching the memory limit of 4 Go.
Same classes are used in 5.6  and it works great.
Also, in 5.6, all 12 cpu threads are at 100% while it bearely hits 40% in php7.
As a result, because of php 7 speed it takes the same time.
I will try a pool collect instead of a start join tomorow.

**Comment by cpugourou** [comment] 2016-01-19 15:53
I found out what is the problem and found a work around.
This is totally my fault.
With V2 it was fine to pass big arrays into the worker (resulting from database queries), to work on them in the workers. Not anymore with V3. 

You must pass as less argument as possible inside the threaded class and perform the queries inside.

In order to contain the memory usage here is what I am Doing, when dealing with a large number of threads based on huge database result arrays.

I am basically wrapping the pool inside a loop in order to avoid the pool size going over the available CPU threads and creating memory overheads. Doing it according to the number of CPU threads allows to cycle across works and unset the pool while it s not so big, keeping the memory usage reasonable.

Also, I have noticed that passing to big arrays into the workers greatly diminish the workers speed (by 60% in my case). Smaller are the passed variables, faster they are.

So basically, I split the pool size exactly to the available CPU treads in a loop and perform every queries inside the workers.
Clearly, V3 needs much more discipline and is less forgiven than V2. My bad and I apologize for the confusion.

    $Nb_of_th = 40; // (2 X 10 cpu cores)
    $global_data = array();
    $variables= array_chunk($variables_list, ($Nb_of_th)); // chuncks per 40

    // loop across chuncks and define pool size per number of threads (40)
    foreach ($variables as $key => $chunks) {
        $pool = new Pool($Nb_of_th, Worker::class);

        foreach (range(1, $count($chunks)) as $i) {
            $pool->submit(new customDamLev_matcher ($chunks[$i - 1]));
        }
    $data = [];
    $collector = function (\Collectable $work) use (&$data) {
        $isGarbage = $work->isGarbage();
        if ($isGarbage) {
            $data[] = $work->result;
        }
        return $isGarbage;
    };    
    do {
        $count = $pool->collect($collector);
        $isComplete = count($data) === $workCount;
    } while (!$isComplete);
      array_push($global_data, $data);
   
     // force immediate purge
     $data=null; unset($data); // garbage intermediate result
     $pool->shutdown();
     $pool=null; unset($pool);// garbage pool
     gc_collect_cycles();// make sure it s done immediately before looping again
    }

I am trying to keep my pthreads as simple as it could be, this is the only way I found to contain the memory under 8Go RAM usage per pool cycle. I do not know if the is good and acceptable practice but it works for me...

In my case: 
PHP 5.6 + pthreads V2: Time to perform 128 loop of 12: 4.5 hours.
PHP 7 + pthreads V2: Time to perform 128 loop of 12: 2 hours.
This is a stunning performance improvement.

Congratulation for your absolutely fantastic work. I do not know how I would do without you.
Regards @krakjoe

**Comment by Jackysi** [comment] 2016-02-26 12:50
I have exactly the same problem. I wrote an simple daemon running in background and collecting data simultaneously and every loop the memory consumption is going up. I made sure that variables and resources are cleaned up to avoid the behavior. I only use 8 threads

**Comment by Jackysi** [comment] 2016-04-13 00:28
no update on this? for me this is really a deal breaker since the extension eats 32GB of RAM if necessary. Takes a few days but still... Restarting daemon every few days just isn't a solution...

**Comment by krakjoe** [comment] 2016-04-13 04:01
I'm not able to reproduce any strange behaviour with the original code in this report.

There has been updates that could have effected it, but I forgot about this report.

I'm going to close the report, please update pthreads to the latest sources and try to reproduce your issue.

Please open a new report if it persists with all the information requested.

**Closed by krakjoe** 2016-04-13 04:01 UTC
Labels: feedback

**Comment by metalwolf** [comment] 2016-04-17 00:43
Perfect @krakjoe , it is now working perfectly on the last pthreads and PHP7 version. Not a single byte lost :D
After 1million threads served with 500 threads in parallel (approx 1 hour), memory still near 800M, same as when the test started.
WAWAS can go to beta - RC production now :)

Thanks !
- Phil
