### ISSUE TITLE
Failed make with Php7.2

### ISSUE THREAD

**Issue by Bixilon** [krakjoe/pthreads#785] opened 2017-12-07 20:46 UTC
I am using phpbrew and I cant install(make) it..

Version: latest

Log:

> 
root@bixilon:~/php-src# tail /root/.phpbrew/build/php-7.2.0/ext/pthreads/build.log

```
> root@bixilon:~/php-src# tail /root/.phpbrew/build/php-7.2.0/ext/pthreads/build.log
> ./classes/pool.h:293:4: warning: passing argument 1 of 'zend_hash_find_ptr' from incompatible pointer type [enabled by default]
> In file included from /root/.phpbrew/php/php-7.2.0/include/php/Zend/zend.h:34:0,
>                  from /root/.phpbrew/php/php-7.2.0/include/php/main/php.h:35,
>                  from ./src/pthreads.h:37,
>                  from /root/.phpbrew/build/php-7.2.0/ext/pthreads/php_pthreads.c:22:
> /root/.phpbrew/php/php-7.2.0/include/php/Zend/zend_hash.h:736:33: note: expected 'const struct HashTable *' but argument is of type 'struct zend_function_entry *'
>  static zend_always_inline void *zend_hash_find_ptr(const HashTable *ht, zend_string *key)
>                                  ^
> make: *** [php_pthreads.lo] Error 1
> make: Leaving directory `/root/.phpbrew/build/php-7.2.0/ext/pthreads'
> 
```

Can you help me?

**Comment by nmapx** [comment] 2017-12-08 17:42
What branch/tag do you use to build pthreads?
PHP7.2 issues are common.

**Comment by kwhat** [comment] 2017-12-16 21:59
I was having trouble building anything other than the trunk for php7.2

**Comment by tpunt** [comment] 2018-01-22 23:17
Are you still having issues with building pthreads from source? Remember that the latest release is not compatible with PHP 7.2 - you must use the master branch instead.

**Comment by tpunt** [comment] 2018-01-31 18:18
Ok, I've tried this and can confirm that you are using the latest release (3.1.6), which is not compatible with PHP 7.2+. Since we already have issues open for making a new release, I am going to close this issue.

**Closed by tpunt** 2018-01-31 18:18 UTC

**Comment by dana321** [comment] 2018-02-13 14:03
Can i just chime in here and say that the following command is confirmed as working as long as you use +zts when building php 7.2 - php 7.1 and 7.0 are not supported by pthreads but 7.2+ is - there was memory leak issues in previous php 7 builds but from what i have read and through testing i think they have been resolved now:

phpbrew ext install https://github.com/krakjoe/pthreads
