### ISSUE TITLE
Segfault when handling PDO exceptions

### ISSUE THREAD

**Issue by angstymeat** [krakjoe/pthreads#703] opened 2017-05-21 02:26 UTC
Environment
==========
**PHP**
PHP 7.1.5 (cli) (built: May  9 2017 18:37:08) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**pthreads**
Version => 3.1.7dev

**OS**
Linux sysname 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Summary
======
I've been trying to figure this out for a week, but I just can't figure out why my code is faulting. It works fine until there are a lot of exceptions trapped with a try / catch block, then it faults. If there are just a few errors it will be ok, but if there are a lot it will eventually segfault.

The interesting thing is that if I do not set "PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION" and just let it return a numeric error code, and use that, it functions correctly.

This is leading me to believe it has something to do with the PDOException object that is returned on a PDO error.

Reproducing Code
==============
This example code is a simplified version of the code that exhibited this problem.  My original code will trigger the problem inline in about 3 seconds, and never has a chance to exit normally.

This simplified version will sometimes do it while it is running, but will always trigger a segfault on exit.

```php
#!/usr/bin/env zts-php
<?php
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class crashThread extends \Thread {

  protected $base;

  public function setBase($base) {
    $this->base = $base;
  }

  /**
   * The crashtest table used below:
   * 
   * CREATE TABLE `crash` (
   *  `id` bigint(20) NOT NULL DEFAULT '0',
   *  `base` bigint(20) NOT NULL DEFAULT '0',
   *  UNIQUE KEY `idx_main` (`id`,`base`)
   * ) ENGINE=InnoDB DEFAULT CHARSET=utf8
   */
  public function run() {
    $db = new \PDO('mysql:host=database.server.name;dbname=crashtest', 'crashtest', 'crashtest', array(
      \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
      )
    );

    $time = time();
    $insert = $db->prepare('INSERT INTO crash (id,base) VALUES (?,?)');
    $val = 1;
    do {
      $val++;
      try {
        echo "Inserting\n";
        $insert->execute(array($val, $this->base));
      }
      catch (Exception $ex) {
        if ($ex->getCode() == '23000') {
          echo "Duplication\n";
        }
      }
    }
    while (time() < $time + 20);
  }

}
$threads = [];
$count = 5;
for ($i = 0; $i < $count; $i++) {
  $threads[$i] = new crashThread();
  $threads[$i]->setBase($i);
  $threads[$i]->start(PTHREADS_INHERIT_NONE);
}

for ($i = 0; $i < $count; $i++) {
  $threads[$i]->join();
}
```
Expected Output
=============
On the first run on an empty table, all of the output should say "Inserting", and the script should end without error.

On the second run an a table populated by the first run, the output will be a combination of "Inserting" and "Duplication". The script should end without error.

> Duplication
> Inserting
> Duplication

Actual Output
============
On the first run on an empty table, all of the output should say "Inserting", and the script should end without error.

On the second execution, this time on a table with entries from the first run, there should be a combination of "Inserting" and "Duplication". This time the script will end with a  segmentation fault.

> Duplication
> Inserting
> Duplication
> Segmentation fault (core dumped)

If the "PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION" line is commented out and you just rely on it returning a numeric result code (bypassing the try / catch), the code works correctly.

**Comment by fuyutsuki** [comment] 2017-05-22 16:26
I also confirmed the same phenomenon in php 7.0.19

**Comment by angstymeat** [comment] 2017-05-22 20:34
Thanks. Nice to know I'm not crazy.

I'm wondering if this has something to do with how PDOException extends RuntimeException and changes the error code from an int to a string.

**Comment by tpunt** [comment] 2017-05-31 18:31
This appears to be another race condition in the engine (related to #696 and possibly #691 (though verification on this is still needed)).

Notes to my future self:

These occur when objects are created in quick succession that reference strings via their properties (and sometimes property names themselves). This is problematic because the reference count for such global strings are being incremented when objects refer to them, but due to race condition problems (multiple threads accessing the same values without locks), some reference count increments are lost. This causes these strings to have a lower reference count than the number of places that actually reference them.

This is problematic because when these objects are gradually destroyed, they decrement the reference count for these strings. When the reference count reaches 0, the zend memory manager (ZMM) for that thread attempts to free the string. This almost always causes a segfault (typically with the message "zend_mm_heap corrupted") because the strings are typically allocated in the main thread (and therefore on the main thread's ZMM heap), but the the deallocation is attempted by a child thread's ZMM. The child thread's ZMM notices a mismatch in the heap address being freed and its own heap addresses, and thinks there's a corruption problem, triggering the bailout.

This problem can, for example, be triggered by the following code too:
```php
<?php

class crashThread extends \Thread
{
    public function run() {
        while (1) {
            try {
                new ReflectionClass('non-existent');
            } catch (Throwable $e) {}
        }
    }
}

$threads = [];
$count = 30;
for ($i = 0; $i < $count; $i++) {
    $threads[$i] = new crashThread();
    $threads[$i]->start(PTHREADS_INHERIT_NONE);
}

for ($i = 0; $i < $count; $i++) {
    $threads[$i]->join();
}
```

In both the above code, and the original code, the exceptions are referencing the file name (which is a global string). The above code will trigger the problem quicker since the exceptions are created in quicker succession (thereby triggering the race condition quicker).

#696 is fixed in PHP 7.2 by some strings being interned (and can possibly be fixed for PHP 7.1 and 7.0 by making a hard copy of all internal classes per thread). I still have yet to look further into #691. The problem seen in this issue (file name referencing) is not fixed in PHP 7.2, since those strings are not being interned. I wonder if we can patch the master branch of php-src to intern these file names.

**Comment by angstymeat** [comment] 2017-05-31 21:16
That's very informative, and explains a lot!

The code I'm working on is in early development and seems to have problems like this when I'm experimenting with error handling in tight loops, and doesn't happen when I'm testing it against our production data.

I'll keep this in mind as work progresses.

**Comment by tpunt** [comment] 2017-07-22 16:37
@krakjoe you may want to have a read of this issue. (I'm currently away on holiday, so I won't have access to a machine for another week.)

**Comment by krakjoe** [comment] 2017-07-24 07:42
Not able to reproduce with latest sources ... if I'm wrong, please re-open ...

**Closed by krakjoe** 2017-07-24 07:42 UTC

**Comment by tpunt** [comment] 2017-08-03 10:48
I could still reproduce the issue, but this has now been fixed in ff792f7.

**Comment by angstymeat** [comment] 2017-08-03 23:14
I was going to test this myself, but I can't compile under PHP 7.1. Looking at the error and the code, it looks like this version is now limited to PHP 7.2+.

Is that the intention? The docs still say PHP 7+.

**Comment by tpunt** [comment] 2017-08-04 07:53
@angstymeat Yes, it is intentional that pthreads can now only be used with PHP 7.2+. ZTS mode on <PHP 7.2 is broken, unfortunately, where there are a lot of race conditions (leading to random crashes).

I'll make a note of this in the documentation tracking issue that pthreads is only compatible with PHP 7.2+ now.

**Comment by angstymeat** [comment] 2017-08-20 18:58
I just wanted to say that I set up a PHP 7.2 dev environment, manually compiled and installed the latest pthreads, and I'm not having issues anymore.

Previously, my program wasn't able to run overnight without getting a segfault, but since I updated it's been running for 3 days without incident. I had been trying to debug whatever was causing it to crash, but it didn't occur to me that it was actually a PHP71/pthreads issue.
