### ISSUE TITLE
Inheriting methods and properties in Worker.

### ISSUE THREAD

**Issue by Zelfapp** [krakjoe/pthreads#432] opened 2015-04-04 18:36 UTC
I'm looking at the code examples and trying to grasp how to use pthreads. I'm running php 5.5x and have pthreads 2.0.10 installed. My applications needs to import multiple databases into elasticsearch asynchronously. Some databases will be contain only a few records and import quickly, while others will contain 10's of thousands and could take a while. I was looking at curl multi, but then found pthreads, which seems to be the better way to go.

However, looking at the code examples I'm not understanding how to make methods and properties of class My_App_Sync available in class Async. Specifically, what I want to do is establish only one connection to both my mongo server and elasticsearch server in My_App_Sync and then have those connections available for each asynchronous job in class Async. E.g. if there are 100 databases I need to import into elasticsearch, I don't want to create 100 connections to mongo and elasticsearch, just one for all imports to work off of.

Further, I'm not even sure simply extending Worker is how you create asynchronous operations where all imports would be running at the same time and independent of one another. So my hope is someone will fill in the blanks and help me to understand how to accomplish my objectives using pthreads. Thanks in advance.

```php
<?php
define('BASEPATH', true);

set_time_limit(0);
error_reporting(E_ALL);

require_once('application/config/appconfigs.php');
require_once('application/config/moreconfigs.php');

class My_App_Sync {
    public $clientElastic;
    public $config;
    public $clientApiKey;
    public $clientSharedSecret;
    public $collection;
    public $runSyncs;
    
    public function __construct($config) {
        $this->config = $config;
        $this->clientApiKey = $this->config['CLIENT_KEY'];
        $this->clientSharedSecret = $this->config['CLIENT_SHARED_SECRET'];
        $this->loadAppMongoCollections();
    }
    
    public function loadAppMongoCollections() {
        $collections = $this->config['MONGO_COLLECTIONS'];
        $collections[] = $this->config['MONGO_COLLECTION_APPCREDS'];
        
        if (!empty($collections)) {
            foreach($collections as $collection) {
                $this->collection[$collection] = $this->load($collection);       
            }
        }
    }
    
    public function load($collection = false) {
        if ($collection !== false) {
            try {
                $connStr = $this->config['MONGO_SERVER'];
                $conn = new MongoClient('mongodb://' . $connStr);
                
                $db = $conn->{$this->config['MONGO_DB']};
                
                return $db->{$collection};
            } catch (MongoConnectionException $e) {
                return false;
            } catch (MongoException $e) {
                return false;
            }    
        }
    }
    
    public function runSync() {
        if ($this->runSyncsFound() === true) {
            $this->initElasticaLibrary();
            $this->callAsync();    
        }
    }
    
    public function runSyncsFound() {
        $this->runSyncs = array();
        
        $query = array(
            'sync' => 'run'
        );

        $cursor = $this->collection['sync_search']->find($query);

        if ($cursor->count() > 0) {
            foreach($cursor as $obj) {
                $this->runSyncs[] = array(
                    'mongo_id' => (string) $obj['_id'],
                    'user_shop' => $obj['user_shop'],
                    'index_version' => $obj['index_version']
                );
            }
        }
        
        if (!empty($this->runSyncs)) {
            return true;
        } else {
            return false;
        }
    }
    
    public function callAsync() {
        foreach($this->runSyncs as $sync) {
            $async = new Async($sync);
            $async->start();
            $async->shutdown();
        }
    }
    
    public function initElasticaLibrary() {
        $params = array('hosts' => $this->config['ES_HOSTS']);
        
        $this->clientElastic = new Elasticsearch\Client($params);
    }
}

class Async extends Worker{
    public $sync;
    
    public function __construct($sync) {
        $this->sync = $sync;
    }
    
    public function run() {
        if ($this->sync) {
            echo 'Hello World!';
            var_dump(function_exists("initElasticaLibrary")); // prints false
            var_dump($this->clientElastic); // prints null
            var_dump($this->collection); // prints null
        }
    }
}

$myAppSync = new My_App_Sync($config);
$myAppSync->runSync();
```

**Comment by JakeFalcor** [comment] 2015-04-07 07:24
In pthreads, sharing of resources between different Threads is potentially dangerous. I believe krakjoe states it a couple of times that you should not attempt to do so. Therefore, you will probably need to start connections on every thread.

Also, I might be wrong, but it seems you're trying to use Worker objects in place of Thread objects. Workers are supposed to be injected with "tasks"/Stackables to work on. (I believe they changed class name in 2.0, now it's called Threaded?)

**Comment by Zelfapp** [comment] 2015-04-07 16:05
Clearly above my understanding at this point. I'm looking into Threaded, but please take a look at my pseudocode to see if I'm even close to the concept here. For my use case, which is to import multiple data stores into my app asynchronously: 

1. My_App_Sync class will simply lookup the sync jobs that need to be run.
2. Then in My_App_Sync, if sync jobs are found, I'll loop through them in the callAsync() method
3. callAsync() will instantiate a new Async object extending Threaded. In callAsync() I can pass in some data from My_App_Sync into Async's __construct, such as the data store to import, when Async is instantiated.
4. However, all functionality such as creating connections to database servers/other servers must be created in my Async class since sharing data is unsafe between threads.

In my callAsync() method, based on the above pseudocode, am I calling the right methods for Threaded to run? Do I need to call shutdown()?
```php
$async = new Async($sync);
$async->start();
$async->shutdown();
```

**Comment by krakjoe** [comment] 2015-08-21 05:24
This is not a bug in pthreads, so closing the issue. This is not the place to get help with code.

**Closed by krakjoe** 2015-08-21 05:24 UTC
