### ISSUE TITLE
Socket::accept() and Socket::setBlocking(false)

### ISSUE THREAD

**Issue by prolic** [krakjoe/pthreads#733] opened 2017-08-06 10:45 UTC
I am not sure if this is the correct behaviour. But once `Socket::setBlocking(false)` is called, a call to `Socket::accept()` throws `RuntimeException: socket found in invalid state`.

When I remove that `setBlocking(false)` call, the thread hangs forever during `accept()` and waits for a connection. This leads to being impossible to shutdown the thread, as I cannot close the socket nor kill the thread (`Thread::kill()` has been removed).

Is this a bug? If not, how should I proceed?

Environment
==========

  * PHP: 7.2.0beta1
  * pthreads: latest master
  * OS: Ubuntu 16.04 LTS

**Comment by SirSnyder** [comment] 2017-08-15 23:45
I guess this is a bug. Should be easy to fix. Will give it a try the next days.

**Comment by SirSnyder** [comment] 2017-08-15 23:48
@tpunt please add the bug label

**Comment by dktapps** [comment] 2017-08-16 07:33
On a semi-related note, this is also a problem with resources... if you have an application with a thread waiting for a blocking stdin read to complete, for example, you can't stop the thread without user input, and are unable to kill it.

**Comment by tpunt** [comment] 2017-08-17 21:19
Reading through the [`accept`](http://man7.org/linux/man-pages/man2/accept.2.html) man page (since `Socket::accept` uses it internally) shows the following:
> If no pending connections are present on the queue, and the socket is
       not marked as nonblocking, accept() blocks the caller until a
       connection is present.  **If the socket is marked nonblocking and no
       pending connections are present on the queue, accept() fails with the
       error EAGAIN or EWOULDBLOCK.**

So it would seem that this is expected behaviour. I cannot offer much more advice on this at the moment, though, because I'm not well-versed in the sockets code (yet). I'll try to look more into this in the coming week.

**Comment by prolic** [comment] 2017-08-18 13:57
Btw: Will is the Tread::kill() method removed? With it I probably could ignore the setBlocking-problem and just kill the thread, when I want to stop the socket server.

**Comment by tpunt** [comment] 2017-08-18 19:32
I can think of two reasons for removing `Thread::kill`:
 1. If a thread acquires one of pthread's global mutexes, and you then kill it, the lock will not be released. This could probably be solved with Robust Mutexes, but it isn't something I've looked into.
 2. Killing a thread will not enable for that thread's memory to be released - it will be leaked until the main PHP process ends.

There could be other problems with it too - the above two points were just my guesses of why it was removed.

**Comment by prolic** [comment] 2017-08-18 19:38
Ok so I need a non blocking socket server, so I can stop him gracefully
then :-)

**Comment by SirSnyder** [comment] 2017-08-24 00:13
@prolic please run your socket server with the master branch of my fork https://github.com/SirSnyder/pthreads. I will provide a merge request, if my patch works for you.

**Comment by prolic** [comment] 2017-08-24 10:36
@SirSnyder I checked out your branch, but `make` fails on my machine.

**Comment by prolic** [comment] 2017-08-24 10:40
I just cloned your repo again and same problem. Also on krakjoe's original master branch. Tested with PHP 7.2.0beta3 on Ubuntu 16.04.

**Comment by prolic** [comment] 2017-08-24 10:45
Oh, nevermind, I just realized I compiled against 7.1.5 accidentally :) Testing now....

**Comment by prolic** [comment] 2017-08-24 10:50
Unfortunately it's not working.

When I do `$this->socket->setBlocking(false);` then later in my thread `$this->threadSocket = $this->mainSocket->accept();` will have `$this->threadSocket` = NULL instead an instance of Socket.

**Comment by prolic** [comment] 2017-08-24 11:23
@SirSnyder you'll find the example here:

https://github.com/prolic/pthreads/blob/socketserver/examples/SocketServer2.php

You only need to add the `setBlocking(false)` yourself, as this is still missing.

**Comment by SirSnyder** [comment] 2017-08-24 23:23
@prolic I've modified your example https://gist.github.com/SirSnyder/c6fb3e3c730957a25bfcc08b836a92a7. Socket::accept() now returns false instead of null to match the behavior of socket_accept().

**Comment by prolic** [comment] 2017-08-25 08:07
@SirSnyder Thanks, but it still doesn't seem to work: `PHP Fatal error:  Uncaught Error: Call to a member function write() on null in /home/sasa/code/pthreads/examples/SocketServer2.php:106`

**Comment by prolic** [comment] 2017-08-25 08:09
Oh wait, I need to add your patch first....

**Comment by prolic** [comment] 2017-08-25 08:10
Wow, works like a charm !!! Thanks a lot !!

**Comment by prolic** [comment] 2017-08-25 14:35
@SirSnyder when you provide your PR, would like to include your updated version of https://github.com/krakjoe/pthreads/pull/734 as well?

**Comment by SirSnyder** [comment] 2017-08-25 21:59
@prolic with pleasure

**Comment by prolic** [comment] 2017-08-26 10:18
@SirSnyder I was experimenting a bit the socket server, and I still have one issue:

Once a connection is established (I use telnet for testing) and I try to stop the server, the server will not stop, until I close or finish the telnet session.

BUT: If I do CRTL+C again on the socket server, the server will stop and telnet connection is closed.

I can't figure out what is going on here, maybe you have an idea?

What I wanted to achieve is giving all clients 5 seconds to complete, but then they will all get kicked (similar to what nginx does, when you stop the server, but have an open telnet connection).

**Comment by SirSnyder** [comment] 2017-08-27 12:25
@prolic yes, it's a very similar situation to the first. The spawned socket is in blocking state, read() and write() are hanging forever. I've updated the [gist](https://gist.github.com/SirSnyder/c6fb3e3c730957a25bfcc08b836a92a7) with the sample server extended.

**Closed** 2018-01-29 15:07 UTC
