### ISSUE TITLE
pthreads 3.1.6 random crashing

### ISSUE THREAD

**Issue by mctracker** [krakjoe/pthreads#593] opened 2016-05-05 10:17 UTC
Here's the windows log message:

```
Faulting application name: php.exe, version: 7.0.6.0, time stamp: 0x57227780
Faulting module name: php7ts.dll, version: 7.0.6.0, time stamp: 0x57227f4d
Exception code: 0xc0000005
Fault offset: 0x00000000000170bb
Faulting process id: 0x9e0
Faulting application start time: 0x01d1a6ad3e402fd0
Faulting application path: C:\php7\php.exe
Faulting module path: C:\php7\php7ts.dll
Report Id: 11816c60-12a1-11e6-8c59-f8169b6275a3

```

PHP: 7.0.6, os:win2k8 x64

start_thread() uses curl and mysqli. 

Here's the part of code that have no dependencies:

```
$workers = [ ];
$t_count = 275;
$flag = 1;
$k = 0;
$perc_diff = 2;
$last_percent = 0;
$connected = true;
$s_time = microtime ( TRUE );    

// StoreResult extends threaded
$result = new StoreResult ();

if($step_two)
	$result->SetStep(2);

while ( $flag === 1 ) {

 
	$c_w = count ( $workers );

	if ($c_w < $t_count) {
		for($i = $c_w; $i < $t_count - $c_w; $i ++) {
			if ($k >= $data_size) {
				$flag = 0;
				break;
			}
			
			if( !$step_two )
				$workers [$i] = new start_thread ( $data [$k],  $result ...  );
			else
				$workers [$i] = new start_thread ( $data [$k], $result ... );
			// echo $data[$k]."\n";
			$workers [$i]->start ();
			
			unset($data [$k]);
			
			$k ++;
			
		}
	}

	$c_w = count ( $workers );
	for($i = 0; $i < $c_w; $i ++) {
		if ($workers [$i]->join ()) {
			// echo "joining $i\n";
			unset ( $workers [$i] );
		}
	}
	
	$arr = $result->GetResults ();
	$valid = $arr [1];
	$e_time = microtime ( TRUE );
	$t = $e_time - $s_time;
	$percent = ($k / $data_size) * 100;
	if (($percent - $last_percent) >= $perc_diff || $percent == 100) {
		$last_percent = $percent;
		
		if( !$step_two )
			SetStatus ( $mysqli_obj, $DB ['worker_table'], 1, "Working", ( int ) $percent, "" );
		else
			 SetStatus ( $mysqli_obj, $DB ['worker_table'], 1, "Rechecking valid domains", ( int ) $percent, "" );
		
		SetProcessed ( $mysqli_obj, $DB ['worker_table'], $k, $step_two );
		SetGoodProcessed ( $mysqli_obj, $DB ['worker_table'], $valid, $step_two );

		echo "progress: " . $percent . " percent ($k of $data_size, valid: $valid) \n";
		echo "time: " . $t . "\n";
	}

	//gc_collect_cycles();
	///sleep(2);
}



```

Is there a way that I can manually debug it? Maybe there's some memory leak or some functions are called too oftern simultaneously?

**Comment by krakjoe** [comment] 2016-05-16 14:43
I need reproducing code.

**Comment by krakjoe** [comment] 2016-09-29 07:09
Closing, because no reproducing code was given.

Feel free to reopen, or re-submit, with all the information requested by the template.

**Closed by krakjoe** 2016-09-29 07:09 UTC
Labels: feedback
