### ISSUE TITLE
uninitialized variable in pool thread

### ISSUE THREAD

**Issue by shyer** [krakjoe/pthreads#456] opened 2015-07-24 09:29 UTC
I run the example `examples/MySQLi.php`, there are 4 worker and 6 work, so 2 work reuse the worker thread, but it seems that the local variable `$rows` also reused, as a result, it merge the old data of the old thread.

I add `var_dump(isset($rows))` in run() function, it will be 6 `false`, but got 4 `false` and 2 `true`.
 
```php
public function run() {
        $mysqli = $this->worker->getConnection();
        
        $result = $mysqli->query($this->sql);
        
        var_dump(isset($rows));
        if ($result) {    
            while (($row = $result->fetch_assoc())) {
                $rows[] = $row;
            }
        }
        
        $this->result = $rows;
    }
```

**Comment by 2072** [comment] 2015-07-24 20:30
The code in a `Threaded::run()` executes in the same context as `Worker::run()`. This is an intended behaviour but one must be careful when using local variables as they keep their existence between tasks.  One can use `Worker::run()` to set such local variables and use them in subsequent submitted tasks.

This is indeed not taken into account in the provided example, `$this->result = $rows;` should be part of the `if` block because as you've observed when there is no result, the rows of the previous task re-added to the result...

**Comment by krakjoe** [comment] 2015-07-26 05:54
> The code in a Threaded::run() executes in the same context as Worker::run().

Fixed in PHP7, it was intended, but unsustainable for this reason and others.

**Closed** 2015-08-05 04:01 UTC
