### ISSUE TITLE
Can't instanciate object

### ISSUE THREAD

**Issue by SidFerreira** [krakjoe/pthreads#438] opened 2015-04-21 18:18 UTC
I have a thread that is trying to create a new Yii's MondoDB object (extends ActiveRecord).
When arrives at this line the code stops.

How to create a new object?

**Comment by krakjoe** [comment] 2015-08-20 10:47
I would have needed reproducing code to help you. Closing, since it doesn't seem forthcoming.

**Closed by krakjoe** 2015-08-20 10:47 UTC
