### ISSUE TITLE
close_socket by thread in run method automatically gives a zend_mm_heap corrupted

### ISSUE THREAD

**Issue by metalwolf** [krakjoe/pthreads#508] opened 2015-10-27 17:23 UTC
Hi KrakJoe, nice job BTW.

Running  the ServerSocket example copied as is, gives a zend_mm_heap corrupted
The problem is the close_socket(), happen whatever you do before, even just close the socket and it gives the PHP error.

This maybe have something to do with the #504 bug, but this one is quite reproducible. 
I detected the same problem on PHP 7.0.0RC2 (tried it too on this compilation and same behaviour)

I already found a work-around: close the socket from outside the thread when it is released (main PHP run don't corrupt the heap when you close the socket) but I guess it's not the supposed "solution".

-- running the example:
[root]# php7 SocketServer.php
zend_mm_heap corrupted

FYI

[root]# php7 --version
PHP 7.0.0RC5 (cli) (built: Oct 23 2015 17:13:33) ( ZTS )

pthreads v 3.0.8

centos 6
[root]# uname -a
Linux thomassigny.org 2.6.32-431.1.2.0.1.el6.i686 #1 SMP Fri Dec 13 11:45:23 UTC 2013 i686 i686 i386 GNU/Linux

**Comment by krakjoe** [comment] 2015-10-28 05:26
I can't reproduce this problem, try not using outdated RC's, build from php-src head.

Resources are officially unsupported, you should not write code that relies on resources.

Some (not too distant) future version of PHP7 will have resources removed. Currently, the plan seems to be to replace resources with (initially) method-less objects. We can't share standard objects, and so any code that relies on sharing resources is going to break.

Zend stream resources are not and never were safe, and they're pretty soon going to be completely useless.

There is a solution to this, we should implement our own thread safe streams layer that integrates with Zend's, or provides a similar functionality ... none of this is exciting to me, I dislike network programming, so I'm not going to work on it until I'm forced ....

I'm going to close the bug as wontfix, because resources are doomed ... as explained ...

**Closed by krakjoe** 2015-10-28 05:26 UTC

**Comment by BurakDev** [comment] 2015-10-29 13:19
C:\php7
λ php demo\SocketServer.php
zend_mm_heap corrupted

C:\php7
λ php -v
PHP 7.0.0RC6 (cli) (built: Oct 27 2015 21:07:04) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

pthreads v3.0.7 (because the build of 3.0.8 failed on Windows)

**Comment by BurakDev** [comment] 2015-10-29 13:50
And I don't understand how the socket_close work on Sockets.php example :disappointed:

**Comment by metalwolf** [comment] 2015-10-29 15:08
I totally agree. @krakjoe, after all, if a feature is *not* supported like stream and sockets, why bother to put them into the examples ? I think so better make a note "this example has been removed because ... etc"

On another hand, @BurakDev, opening a socket is actually like openning a file, it's a stream and it's thread unsafe, that's correct.I analized the PHP source code yesterday after @krakjoe closed the ticket, you'll see the streams use the heap directly (so the reazon of corruption of the heap while threaded, there are no mutex, locks, or safe use of the memory space).

I other words, you will rarely have a corruption on file since you open it, write it (or read it) and close it fast. Sockets are exactly the contrary, you open then and keep them opened a loooooong time and will surely make misuse with them, like passing them to another thread and corrupt anything. 

So the message is NEVER EVER open a stream in a thread, and close it into another thread. Always do it into the same thread to avoid local and global corruption.

I personally did not make the test, but pretty sure if you open a file in thread 1, read it in thread 2 and close it in thread 3, this will probably corrupt the heap as well on the same way.

After all it's like C and other languages, when you use threads, use them wisely and understand what is going inside. As in C it's extremely easy to corrupt memory, heap, piles, variables, etc. in a multithreaded environment. And it's the task of the programmer to make it good.  

I agree with @krakjoe after watching into the PHP source, sockets streams are very thread unsafe if you start to share them between threads.

That does not mean you cannot use socket streams, that just means use them correctly, while they are still available at least.

Keep the create socket/open socket and close socket on the same thread and that should be relatively stable.

Somebody really need to make a socket thread safe class (did I name myself maybe someday ?)
Or if anybody already did some, or some job in this way, tell me.

Anyway, good luck.

**Comment by 2072** [comment] 2015-10-29 22:45
I agree, I'm still using pthreads 2 but I managed to use raw sockets successfully by doing the following:
- As said above, the thread that creates a socket is the one that closes it.
- The thread that opens the socket and closes it does nothing else with the socket, it doesn't use it in any way while the other worker thread it's shared with might use it.
- Only one thread is using the socket at a given time (you must make sure of that).
- The socket is closed only when nothing else is using it / referencing it any more. ie: All other threads must explicitly destroy their reference to the resource before the main thread closes it, this must not be left to the garbage collector...

My code is perfectly stable and is able to run for months in a row and handle millions of query. So it's possible but it's difficult.

**Comment by BoltUser** [comment] 2018-07-25 20:10
hi @krakjoe sorry but i have the some problem, you know when this bug/proble is fixed?
