### ISSUE TITLE
Using thread pool inside threads.

### ISSUE THREAD

**Issue by userqq** [krakjoe/pthreads#764] opened 2017-10-05 02:09 UTC
### Environment
PHP 7.2.0-dev (cli) (built: Oct  5 2017 04:45:13) ( ZTS DEBUG )
Pthreads 3.1.7dev

Reproducing Code v1
==============
```php
class J extends Thread {
    public function run() {
        sleep(1);
        echo 'Job is done' . PHP_EOL;
    }
}

class T extends Thread {
    public function run() {
        $pool = new Pool(2, W::class);
        for ($i = 0; $i < 5; $i++) {
            $pool->submit(new J());
        }
    }
}

class W extends Worker {
    public function start(?int $options = null) {
        echo 'W::start' . PHP_EOL;
        return parent::start($options);
    }
}

$t1 = new T();
$t2 = new T();

$t1->start() && $t2->start();
```

### Expected Output & Actual Output
```
W::start
W::start
W::start
W::start
Job is done
Job is done
Job is done
Job is done
Job is done
Job is done
Job is done
Job is done
Job is done
Job is done
```

Everything is ok, we have two thread pools and them works correctly.
But what if we try to assign object of Pool to object's property?

Reproducing Code v2
==============
```php
class J extends Thread {
    public function run() {
        sleep(1);
        echo 'Job is done' . PHP_EOL;
    }
}

class T extends Thread {
    public $pool;
    public function run() {
        $this->pool = new Pool(2, W::class);
        for ($i = 0; $i < 5; $i++) {
            $this->pool->submit(new J());
        }
    }
}

class W extends Worker {
    public function start(?int $options = null) {
        echo 'W::start' . PHP_EOL;
        return parent::start($options);
    }
}

$t1 = new T();
$t2 = new T();

$t1->start() && $t2->start();
```
### Unxpected Output
```
W::start
W::start
Job is done
Job is done
W::start
W::start
Job is done
Job is done
W::start
W::start
Job is done
Job is done
W::start
W::start
Job is done
W::start
Job is done
W::start
Job is done
Job is done
```
As we can see pthreads recreates workers for each new job.

**Comment by tpunt** [comment] 2018-01-31 13:51
This is actually quite expected behaviour. `Pool`s are  just an abstraction over `Worker`s - they themselves are not `Threaded` classes. Because of this, they will be serialised when being assigned to a property of a `Threaded` object. When fetching that property, it will cause the string representation of the `Pool` object to be deserialised back to a new `Pool` object.

This can result in some odd-looking behaviour, as you have observed. Issue #767 is also similar to this problem, and I don't think there's anything that can be done about it (that's just how things work).

**Closed by tpunt** 2018-01-31 13:51 UTC
